### ISSUE TITLE
如何在sqlite中转移配置

### ISSUE THREAD

**Issue by GrayXu** [ZeroDeng01/one-api-db-transfer#1]
sqlite没有SQL_DSN，如何指定sqlite file path？  
谢谢

**Comment by ZeroDeng01** [comment]
直接填你sqlite数据文件地址
sqlite你测一下，我这边没达sqlite环境测试，有问题及时反馈

**Comment by GrayXu** [comment]
报错如下
```
./db-transfer-windows-amd64.exe "sqlite3://one-api.db" "sqlite3://new-one-api.db"
2024/06/20 21:00:41 无法连接到数据库: invalid DSN: missing the slash separating the database name
```

抱歉不太熟悉go，`sql.Open`是不是直接操作filepath?

**Comment by ZeroDeng01** [comment]
> 报错如下
> 
> ```
> 
> ./db-transfer-windows-amd64.exe "sqlite3://one-api.db" "sqlite3://new-one-api.db"
> 
> 2024/06/20 21:00:41 无法连接到数据库: invalid DSN: missing the slash separating the database name
> 
> ```
> 
> 
> 
> 抱歉不太熟悉go，`sql.Open`是不是直接操作filepath?

新版已经在更新，手册同步更新，可以试一下

**Comment by GrayXu** [comment]
谢谢，这个版本的逻辑是工作正常的。
